spring:
  application:
    name: item-service
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 192.168.126.128
    port: 5672
    #virtualHost: /pd
    username: admin
    password: admin
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://eurekaone:2001/eureka,http://eurekatwo:2002/eureka


