spring:
  application:
    name: order-service
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 192.168.126.128
    port: 5672
    #virtualHost: /pd
    username: admin
    password: admin
server:
  port: 8201
eureka:
  client:
    service-url:
      defaultZone: http://eurekaone:2001/eureka,http://eurekatwo:2002/eureka
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

