spring:
  application:
    name: zuul
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 192.168.126.128
    port: 5672
    #virtualHost: /pd
    username: admin
    password: admin
  zipkin:
    sender:
      type: rabbit
server:
  port: 3001
ribbon:
  ReadTimeout: 1000
  ConnectionTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
eureka:
  client:
    service-url:
      defaultZone: http://eurekaone:2001/eureka, http://eurekatwo:2002/eureka
zuul:
  routes:
    item-server:
      path: /item-service/**
      serviceId: item-service
    user-server: /user-service/**
    order-server: /order-server/**
  retryable: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream